language: python
sudo: required
python:
- '2.7'
install:
- sudo apt-get update
script: true
jobs:
  include:
  - stage: docs
    if: fork = false AND branch = "master"
    install:
    - sudo apt-get update
    - pip install sphinx==1.7.5 sphinx-autobuild==0.6.0 sphinxcontrib-httpdomain==1.5.0  sphinxcontrib-programoutput==0.11
    - RASABASTER=rasabaster-0.7.17.tar.gz
    - curl -sSL -o $RASABASTER "https://storage.googleapis.com/docs-theme/${RASABASTER}?q=$(date +%s%N)"
    - pip install $RASABASTER
    - pip list
    script:
    - eval "$(ssh-agent -s)"; touch platform_docs_key; chmod 0600 platform_docs_key
    - openssl aes-256-cbc -K $encrypted_bd37f77887e8_key -iv $encrypted_bd37f77887e8_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - chmod 0600 id_rsa
    - ssh-add id_rsa
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
    - export ${!TRAVIS*}
    - cd docs
    - make dirhtml
    - cd ../
    - git clone -b newdocs "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git" newdocs
    - cd newdocs
    - cp -R ../docs/_build/dirhtml/* ./
    - git add -A .
    - git commit -m "[ci skip] Autodoc commit for $COMMIT."
    - git push -q origin newdocs
  - stage: trigger website build
    script:
    - openssl aes-256-cbc -K $encrypted_bd37f77887e8_key -iv $encrypted_bd37f77887e8_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - ssh-add website_push
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git clone -b master --single-branch git@github.com:RasaHQ/rasa-website.git
    - cd rasa-website
    - git commit --allow-empty -m "trigger nlu docs update"
    - git push origin master