language: python
sudo: required
python:
- '2.7'
install:
- sudo apt-get update
script: true
jobs:
  include:
  - stage: docs
    if: fork = false
    install:
    - sudo apt-get update
    - pip install sphinx==1.7.5 sphinxcontrib-versioning==2.2.1 sphinx-autobuild==0.6.0 sphinxcontrib-httpdomain==1.5.0  sphinxcontrib-programoutput==0.11
    - pip install git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RasaHQ/rasabaster.git#egg=rasabaster
    - pip list
    script:
    - eval "$(ssh-agent -s)"; touch platform_docs_key; chmod 0600 platform_docs_key
    - openssl aes-256-cbc -K $encrypted_bd37f77887e8_key -iv $encrypted_bd37f77887e8_iv -in id_rsa.enc -out id_rsa -d
    - ssh-add id_rsa
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
    - export ${!TRAVIS*}
    - sphinx-versioning push -r master docs newdocs .
